// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcy88bxwDs30ImsMvnqnX-UpwOapzqka4',
    appId: '1:419151198841:web:e8b4f2b483ad0b9470f2a8',
    messagingSenderId: '419151198841',
    projectId: 'blog-mag-d37a8',
    authDomain: 'blog-mag-d37a8.firebaseapp.com',
    storageBucket: 'blog-mag-d37a8.appspot.com',
    measurementId: 'G-V4WQLRR7SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVIi1IN41wDY2kIygnVIFIooyXrR_dcMk',
    appId: '1:419151198841:android:34ac078e1ad81af370f2a8',
    messagingSenderId: '419151198841',
    projectId: 'blog-mag-d37a8',
    storageBucket: 'blog-mag-d37a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUbOEDQfeuwzVAF2nbKOu6a4yzE2fZKE',
    appId: '1:419151198841:ios:4a511da0aabc55a970f2a8',
    messagingSenderId: '419151198841',
    projectId: 'blog-mag-d37a8',
    storageBucket: 'blog-mag-d37a8.appspot.com',
    androidClientId: '419151198841-1nb94ka7l88nq3cfg04n19lr6qjllgsk.apps.googleusercontent.com',
    iosClientId: '419151198841-ufm683s9sluv18ivcg97ma2if1jhecpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUbOEDQfeuwzVAF2nbKOu6a4yzE2fZKE',
    appId: '1:419151198841:ios:bc3a480dfb3b154770f2a8',
    messagingSenderId: '419151198841',
    projectId: 'blog-mag-d37a8',
    storageBucket: 'blog-mag-d37a8.appspot.com',
    androidClientId: '419151198841-1nb94ka7l88nq3cfg04n19lr6qjllgsk.apps.googleusercontent.com',
    iosClientId: '419151198841-e39kg4fde0lr8o4si96qhmns02kh8crp.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogChat.RunnerTests',
  );
}
