const Map<String, String> en = {
  'login': 'Login',
  'register_now': 'Register now',
  'register': 'Register',
  'register_screen': 'Register Screen',
  'username': 'Username',
  'password': 'Password',
  'email': 'Email',
  'login_screen': 'Login Screen',
  'e_e': 'Enter email',
  'e_p': 'Enter password',
  's_w_g': 'Sign in with Google',
  'e_d_n': 'Enter display name',
  'select_image': 'Select image',
  'error': 'Error',
  'p_e_e_a_p': 'Please enter email and password',
  'p_s_i': 'Please select an image',
  'e_e_a_p': 'Error email or password',
  'e_login': 'An error occurred while logging in',
  'e_o': 'an error occurred',
  'a_f_r': 'All fields are required',
  'search': 'Search',
  'new_chat': 'New Chat',
  'create_group': 'Create Group',
  'enter_group_name': 'Enter group name',
  'create': 'Create',
  'seleted': 'Selected',
  'profile': 'Profile',
  'sign_out': 'Sign out',
  'gemini_message_1':
      'This chat depends on individual questions and cannot remember previous questions or answers.',
  'e_m': 'Enter your message',
  'no_messages': 'No messages',
  'offline': 'Offline',
  'online': 'Online',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'not_m_g': 'You are not a member of the group',
  'admin': 'Admin',
  'owner': 'Owner',
  'member': 'Member',
  'members': 'Members',
  'exit_the_group': 'Exit the group',
  'are_you_sure': 'Are you sure?',
  'yes': 'Yes',
  'no': 'No',
  'delete': 'Delete',
  'add_member': 'Add as member',
  'add_admin': 'Add as admin',
  'cancel': 'Cancel',
  'exists': "Exists",
  'edit_profile': 'Edit profile',
  'update': 'Update',
  'no_user_found': 'No user found',
  'display_name': 'Display name',
  'my': 'My',
  'm_remove_u_1': 'Are you sure you want to remove this user ?',
  'remove': 'Remove',
  'edit_name': 'Edit name',
  'message': 'Message',
  'am': 'AM',
  'pm': 'PM',
  'new_version': 'New version available! Please update the app.',
  'copy_update_link': 'Copy Update link',
  'close': 'Close',
  'stopped_working_message':
      'This version of the application has stopped working.',
  'version': 'Version',
  'update_available': 'Update Available!',
  'app_no_works':
      'The application has been suspended for maintenance, and work is underway to restore it as soon as possible',
  'download': 'Download',
  'latest': 'Latest',
  'no_versions': 'No versions',
  'privacy': 'Privacy',
};
